version: "3"
services:
  postgres:
    image: library/postgres:16
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  server:
    build: .
    container_name: server
    ports:
      - "5051:5051"
    command: ["./app", "-c", "./cmd/config_local.yaml"]
    depends_on:
      - postgres

volumes:
  db-data: