version: "3"
services:
  postgres:
    image: library/postgres:16
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: server
    restart: on-failure
    ports:
      - "5051:5051"
    command: ["./app", "-c", "./cmd/config_local.yaml"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persons
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data: